### PR TITLE
WIP "eurobot for beginners"

### PR DESCRIPTION
**Pull request by antoinealb**
I want to write an article containing general advices for Eurobot beginners who want to have a reasonable chance at their first try. Opening the PR so we can discuss it early on.

### CODE REVIEW

**Comment by SyrianSpock** [comment]
Good idea

**Comment by msplr** [comment]
Some ideas for electronics that come to mind:
- always keep spare parts on stock for when you fry a chip/board the night before the cup
- choose your microcontroller according to user base and availability of open tools (compiler, debugger). 
- have a working prototype before ordering a PCB
- errors in your hardware design are expensive and can cost a lot of time -> do a design review & verification

**Comment by SyrianSpock** [comment]
- More important than keeping spare parts: keep spare boards
- A good rule of thumb for spares is to have at least 2 spares when making a few board: If you need 1, make 3. If you need more than 10, aim for 30% spare: if you need 10, make 15.

**Comment by antoinealb** [comment]
Good points. Do you think we should go in more "technical details", such as suggesting Cortex-M or even STM32 ?

We should write that spares can seem costly but should be accounted in the base price of the board.

Another team published a list of advice, maybe that could give us ideas as well: http://fribotte.free.fr/bdtech/Conseils/conseils.html

**Comment by antoinealb** [comment]
>  keep spare boards

Plus it makes some nice devkit for your programmers, who are probably more numerous than your robots.

Other ideas:
- Do not do things precipitately (bad solders, no connectors, etc.). It will reduce reliability, make debugging a nightmare and the robot will go through a lot of rough manipulations.
- Communicate a lot and document everything.
- It should not be possible to confuse connectors.
- **Non optional** Use a version control system. It doesn't matter which one, but Git or Mercurial are good choices because of their distributed nature. Avoid Subversion if you can, and never use CVS. Also a good place to store your electronics.
- (that one might be obvious so we could skip it) Write _good_ code, with clear name, comments where necessary, etc.
- Something about unit tests ? It might be too much for a newcomer team.
- Integrate often.

**Comment by SyrianSpock** [comment]
> Communicate a lot

But never prolongate meetings more than they need. Once you're done updating the team or solving your problem, go back to work.

> and document everything.

But don't over document. You'll need keep track of everything so try having fewer documents and don't be too verbose. Lists and drawings are usually preferred to long paragraphs.

> (that one might be obvious so we could skip it) Write good code, with clear name, comments where necessary, etc.

Optimise the reader, not the writer.

> Something about unit tests ? It might be too much for a newcomer team.

Maybe too early. We could write something about it later in a separate article.

> Integrate often.

That brings us back to the idea of focussing on a good wheelbase. You should try to make your robot rolling as soon as possible and build upon it.

**Comment by msplr** [comment]
> Something about unit tests ?

Yes, mention unit tests, but suggest developing hardware independent modules that can be tested on your own system. (Because debugging faulty software on an embedded system is often a nightmare.)

> Integrate often.

integrate early, aim for a minimal functioning program.

About code quality:
- mention code reviews.
- working in pairs results in better code and faster progress.

**Comment by antoinealb** [comment]
Okay, working on an updated draft atm.

**Comment by antoinealb** [comment]
> working in pairs results in better code and faster progress.

Is this exclusive to software though ?

**Comment by msplr** [comment]
> > working in pairs results in better code and faster progress.
> 
> Is this exclusive to software though ?

Actually no, it's quite the same for electronics.

**Comment by antoinealb** [comment]
updated draft

**Comment by msplr** [comment]
Another thing about communication:
Currently at CVRA, those who design the electronics boards also write the software running on them.
This may not be the case for other teams. This is why we should also mention the interaction between the electronics guys and the programmers.
It helps defining the needs, find ideas for new features, compatibility of HW&SW, basic understanding of how things work, etc...

(for the mechanics it's probably similar; I just can't speak for them, though)

**Comment by antoinealb** [comment]
Good point. I don't know what solution to recommend though, as we are not experiencing the problem at the club.

**Comment by msplr** [comment]
> updated draft

looks good to me.

Perhaps, as you mentioned, we could be more specific on some points.
The next days, I'll try to think of something to add.

**Comment by antoinealb** [comment]
Maybe add something about simulation as well.

**Comment by SyrianSpock** [comment]
Something like this:

Don't try to develop everything in simulation and don't try to write your own complete simulator.
Simulate when needed, simulation won't replace integration. Remember that you still need to integrate often.
When the system and behaviors are simple you can hack something to test your ideas, but in the long run you might benefit from a more standard simulator (such as Gazebo, MORSE or Webots).

**Comment by antoinealb** [comment]
I think we should also mention that simulation is great for _integration_ testing, but it doesn't replace _unit_ testing

**Comment by antoinealb** [comment]
Closing as nobody is working on this

**Pull request closed without merging**
