### PR TITLE
Add technologies index and CAN dongle page

### PR DESCRIPTION
**Pull request by SyrianSpock**
screenshot from 2018-01-01 14 15 03

### CODE REVIEW

**Comment by antoinealb** [comment]
What do you think of naming the pages "Bootloader", "Motor board", and so on ? Right now I feel like the CAN wording is a bit too present :p I would keep it just for the dongle

**Comment by antoinealb** [comment]
Also I can take some better pictures if you want, I have the boards at home. The dongle & IO are particularly blurry.

**Comment by antoinealb** [comment]
Other than those two nitpicks, good job !

**Comment by SyrianSpock** [comment]
There you go. I let you take better pictures. My phone camera is shitty.

**Comment by SyrianSpock** [comment]
One minor things that needs fixing is the topbar. It seems that About Us / Contact are wrapped under the topbar (so we don't see them) and I don't know how to fix it.

screenshot from 2018-01-01 14 54 54

**Comment by antoinealb** [comment]
It also messed up the titles :( screen shot 2018-01-01 at 16 04 02

**Comment by antoinealb** [comment]
I took new pictures, they are Okay-ish. but at least not blurry.

**Pull request merged**
