### PR TITLE
Integrate photo albums

### PR DESCRIPTION
**Pull request by antoinealb**
So I started working on a photo album integration. The layout is more or less complete, now I need to take all the google photos albums and link them. I could not get the Picasa API to work, so we will have to keep it synced by hand for now.

Here is what the current layout looks like, what do you guys think ?
screen shot 2016-06-12 at 17 01 59

### CODE REVIEW

**Comment by JackBender** [comment]
Ok, +1

**Comment by antoinealb** [comment]
Ok, I think it is ready for merge. @SyrianSpock @JackBender, review and merge please ?

**Comment by antoinealb** [comment]
Page looks like this now: screen shot 2016-06-12 at 23 24 17

**Comment by SyrianSpock** [comment]
LGTM

**Pull request merged**
